### ISSUE TITLE
[v2] Better support for Custom Code Highlight

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#55]
Another tricky one.
We need to find a way to support others code highlight settings (other `b2/bw`).
Maybe v0.43 [Hugo Piper](https://gohugo.io/news/0.43-relnotes/) can help us here.

**Comment by khos2ow** [comment]
I volunteer for this one, you can assign it to me.

**Comment by luizdepra** [comment]
I think this one is already solved. Needs testing.

**Comment by luizdepra** [comment]
@khos2ow, did you find any issues after the SCSS refactor?

**Comment by khos2ow** [comment]
I have an override of this on my own site, and try to send a PR sometime soon. The thing is this essentially will become a personal opinion of which one to choose and I don't think it makes sense to make this configurable (may be only a wiki on how to override it).

**Comment by luizdepra** [comment]
Ok. Need to test ti again. But I think this problem is already solved.

**Comment by luizdepra** [comment]
I think we s till need a styling refactor.
I want something like code boxes from this [site](https://fasterthanli.me/articles/so-you-want-to-live-reload-rust). Maybe we should test with a border, but I really want to show the language name.

**Comment by clement-pannetier** [comment]
Hi @luizdepra, I've been testing some implementations. I still have issues with colors with dark mode and styles used, but here is an example:

![image](https://user-images.githubusercontent.com/35581688/97194118-10e11e00-17aa-11eb-8bb0-e4f1cd3ceedc.png)

To do this I overrided the default highlight shortcode and added an element to show the language.
Hugo now uses Chroma so I removed the default Pygments configs but added this one `pygmentsUseClasses=true` because I need to generate the [stylesheet for the styles](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css) in order to use these classes to style the language element. The only problem, we need to load the stylesheet file with the `customCss` config property to work by default.

One more problem, overriding the highlight shortcode don't work when using code fences :/
